### ISSUE TITLE
/disguise abra 

### ISSUE THREAD

**Issue by TheBlur21** [ObliqueNET/Server#521]
Hi my name is TheBlur21 I was running around and did /disguise into a abra and it started to tp around like crazy i think because usually the abras tp away from people when you get close that when you disguise as one  it kinda gose crazy it’s funny but ya

**Comment by Rasgnarok** [comment]
This should be fixed, can you confirm @Hiroku ?

**Comment by TheBlur21** [comment]
its still not sadly fix the abras keep tping i decided to test if it worked yesterday when i was joking around with epix.

**Comment by Hiroku** [comment]
Potentially fixed on next restart through pure guesswork
